version: '3.6'
services:

  #-----------------------------------------------------------------------------
  # NGINX
  #-----------------------------------------------------------------------------

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/config/nginx.conf:/tmp/default.template
      - ./site:/var/www/html:rw,cached
    depends_on:
      - wordpress
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${APP_NAME}\.test/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'

  #-----------------------------------------------------------------------------
  # MySQL
  #-----------------------------------------------------------------------------

  mysql:
    container_name: ${APP_NAME}-mysql
    image: mariadb
    volumes:
       - './data:/var/lib/mysql:delegated'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '3306:3306'

  #-----------------------------------------------------------------------------
  # Wordpress
  #-----------------------------------------------------------------------------

  wordpress:
    container_name: ${APP_NAME}-wordpress
    build:
      context: ./docker/wordpress
    volumes:
      - ./site:/var/www/html:rw,cached
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    environment:
      - DB_NAME=wp
      - DB_USER=wp
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PREFIX=wp_
      - WP_ENV=development
      - WP_HOME=http://$APP_NAME.test
      - WP_SITEURL=http://$APP_NAME.test/wp

  #-----------------------------------------------------------------------------
  # PHPMyAdmin
  #-----------------------------------------------------------------------------

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./docker/config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - '8080:80'
    links:
      - mysql:mysql

  #-----------------------------------------------------------------------------
  # Mailhog
  #-----------------------------------------------------------------------------

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
